### ISSUE TITLE
Setting OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET

### ISSUE THREAD

**Issue by kmoy1** [authentik-community/sdk-integrations#2]
In settings.py, how are you setting environment variable values for OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET? I understand the values are from an OAuth2 provider separate from the Django app, but how do you set those values here? I understand the security-related purpose of using env vars instead of checking them in directly- but I am confused on the correct way to set these values.

**Comment by rissson** [comment]
Well that depends on how you run the app, but `OIDC_RP_CLIENT_ID=mylcientid OIDC_RP_CLIENT_SECRET=myclientsecret ./manage.py runserver` should work.

Note however that the way environment variables are retrieved in this example is in no way production ready.
